#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# start IBUS at here
#ibus-daemon -rxRd &
#export PATH="$HOME/.local/bin/scripts:$PATH" # -> chua file run-blocks

xrandr --output Virtual-1 --mode 1360x768 --rate 60 # Set DPI. User may want to use a larger number for larger screens.
#xrandr --dpi 96                      # Set DPI. User may want to use a larger number for larger screens.

clipboard-tray &
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

# Bogo tieng viet - DUNG Fcitx5
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5
export INPUT_METHOD=fcitx5
export SDL_IM_MODULE=fcitx
# export GLFW_IM_MODULE=ibus

# Nghia fix -> error qquit -> re-login -> audio error <- waiting pipewire start
# chay lenh sau va comment "pipewire &"
#systemctl --user start pipewire pipewire-pulse wireplumber
#systemctl --user enable pipewire pipewire-pulse wireplumber

#pipewire &
#sleep 0.5

autostart="mpd xcompmgr dunst unclutter remapd"

for program in $autostart; do
  pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# run script for statusbar
# start-dwmblocks &
# run-blocks &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

#fcitx5 -d &
