#!/bin/sh

# 1. Load Biến môi trường (Environment Variables)
[ -f "$XDG_CONFIG_HOME/shell/env" ] && . "$XDG_CONFIG_HOME/shell/env"

# 2. Load Aliases
[ -f "$XDG_CONFIG_HOME/shell/aliasrc" ] && . "$XDG_CONFIG_HOME/shell/aliasrc"

# 3. Load Functions
[ -f "$XDG_CONFIG_HOME/shell/funcrc" ] && . "$XDG_CONFIG_HOME/shell/funcrc"

# 4. Auto Startx (Chỉ chạy ở TTY1 và chưa có đồ họa)
# Logic này hoạt động trên cả Arch, Void và NixOS
if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
    # Kiểm tra xem Xorg đã chạy chưa để tránh loop
    if ! pgrep -x "Xorg" >/dev/null; then
        exec startx
    fi
fi
